<template>
  <div>
    <div class="container mx-auto">
      <h1>Stores</h1>
      <h1>{{ workspaceId }}</h1>

      <div class="flex justify-end">
        <button
          @click="addStaff"
          class="rounded bg-blue-600 px-8 py-2 my-2 text-sm font-medium text-white"
        >
          Add Store +
        </button>
      </div>
      <div class="rounded-lg border border-gray-200">
        <table class="min-w-full bg-white divide-y-2 divide-gray-200 text-sm">
          <thead class="bg-gray-100 border rounded-lg text-left">
            <tr>
              <th class="py-2 border-r px-4 font-normal">Id</th>
              <th class="py-2 border-r px-4 font-normal">Name</th>
              <th class="py-2 px-4 border-r font-normal">Address</th>
              <th class="py-2 border-r px-4"></th>
              <th class="py-2 border-r px-4"></th>
              <th class="py-2 px-4"></th>
            </tr>
          </thead>

          <tbody>
            <tr v-if="isAddingStaff">
              <td class="py-2 px-4">
                <input
                  type="text"
                  disabled
                  value="autogenerated"
                  class="w-full h-full border-2 rounded-md border-gray-500 bg-transparent py-2 px-4 m-0"
                />
              </td>
              <td class="py-2 px-4">
                <input
                  type="text"
                  v-model="newStoreName"
                  class="w-full h-full bg-transparent border-2 rounded-md border-blue-500 py-2 px-4 m-0"
                />
              </td>
              <td class="py-2 px-4">
                <input
                  type="text"
                  v-model="newStoreAddress"
                  class="w-full h-full border-2 rounded-md border-blue-500 bg-transparent py-2 px-4 m-0"
                />
              </td>

              <td class="py-2 px-4">
                <button @click="addStoreOnDB" class="text-blue-700">
                  Save
                </button>
              </td>
              <td class="py-2 px-4">
                <button @click="cancelAddStaff" class="text-red-700">
                  Cancel
                </button>
              </td>
              <td class="py-2 px-4"></td>
            </tr>

            <tr v-for="(store, index) in stores" :key="store.id">
              <td class="py-2 px-4">{{ store.id }}</td>

              <td v-if="editingIndex === index" class="py-2 px-4">
                <input
                  type="text"
                  v-model="editableStore.name"
                  class="w-full h-full bg-transparent border-2 rounded-md border-blue-500 py-2 px-4 m-0"
                />
              </td>
              <td v-else class="py-2 px-4 text-gray-500">{{ store.name }}</td>

              <td v-if="editingIndex === index" class="py-2 px-4">
                <input
                  type="text"
                  v-model="editableStore.address"
                  class="w-full h-full border-2 rounded-md border-blue-500 bg-transparent py-2 px-4 m-0"
                />
              </td>
              <td v-else class="py-2 px-4 text-gray-500">
                {{ store.address }}
              </td>

              <!-- Edit/Save and Cancel Buttons -->
              <td class="py-2 px-4">
                <button
                  v-if="editingIndex === index"
                  @click="saveEdit(store.id)"
                  class="text-blue-700"
                >
                  Save
                </button>
                <button
                  v-else
                  @click="editStore(store, index)"
                  class="text-blue-700"
                >
                  Edit
                </button>
              </td>
              <td class="py-2 px-4">
                <button
                  v-if="editingIndex === index"
                  @click="cancelEdit"
                  class="text-red-700"
                >
                  Cancel
                </button>
                <button v-else class="text-blue-700">View</button>
              </td>
              <!-- <td v-if="editingIndex === -1" class="py-2 px-4">
                <button class="text-blue-700">View</button>
              </td> -->
              <td v-if="editingIndex === -1" class="py-2 px-4">
                <button @click="confirmDelete(store.id)" class="text-red-700">Delete</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div
        v-if="showModal"
        class="fixed z-10 inset-0 overflow-y-auto flex items-center justify-center"
      >
        <div class="bg-black bg-opacity-50 absolute w-full h-full"></div>
        <div
          class="bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full border-2 border-gray-200"
        >
          <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
            <div class="sm:flex sm:items-start">
              <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
                <h3 class="leading-6 text-gray-900">
                  Are you sure you want to delete?
                </h3>
              </div>
            </div>
          </div>
          <div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
            <button @click="handleDelete" class="text-red-600 px-4 py-2 rounded">Yes</button>
            <button class="text-black px-4 py-2 rounded">No</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { useAuthStore } from "~/store/auth";
import { supabase } from "../supabase/supabase";
const authStore = useAuthStore();
const user = authStore.user;
let stores = ref(null);
let newStoreName = ref("");
let newStoreAddress = ref("");
let editingIndex = ref(-1); // -1 means no editing
let editableStore = ref({});
let idToDelete = ref(null);
const props = defineProps({
  workspace_id: { type: Number, required: true },
});
const workspaceId = computed(() => {
  return props.workspace_id;
});

const getWorkspaceStores = async () => {
  const { data, error } = await supabase
    .from("stores")
    .select("*")
    .eq("workspace_id", workspaceId.value);

  if (data) {
    stores.value = data;
  }
};

onMounted(getWorkspaceStores);

const addStoreOnDB = async () => {
  const { error } = await supabase.from("stores").insert({
    name: newStoreName.value,
    address: newStoreAddress.value,
    workspace_id: workspaceId.value,
  });

  if (!error) {
    newStoreName.value = "";
    newStoreAddress.value = "";
    isAddingStaff.value = false;
    // Refresh the store list
    await getWorkspaceStores();
  } else {
    console.error(error);
  }
};

let isAddingStaff = ref(false);
let showModal = ref(false);

function addStaff() {
  isAddingStaff.value = true;
}
function cancelAddStaff() {
  isAddingStaff.value = false;
}

// Method to initiate editing a store
function editStore(store, index) {
  editingIndex.value = index;
  editableStore.value = { ...store };
}

// Method to save the edited store
const saveEdit = async (storeId) => {
  const { error } = await supabase
    .from("stores")
    .update({
      name: editableStore.value.name,
      address: editableStore.value.address,
    })
    .eq("id", storeId);

  if (!error) {
    await getWorkspaceStores();
    editingIndex.value = -1;
  } else {
    console.error(error);
  }
};

// Method to cancel the editing
function cancelEdit() {
  editingIndex.value = -1;
}

function confirmDelete(id) {
  idToDelete.value = id;
  showModal.value = true;
}

function cancelDelete(){
    idToDelete.value = null;
    showModal.value = false;
}

const handleDelete = async () => {
  const { error } = await supabase
    .from("stores")
    .delete()
    .eq("id", idToDelete.value);

  if (!error) {
    showModal.value = false;
    await getWorkspaceStores();
  } else {
    console.error(error);
  }
};


</script>
